version: "3.2"

services:
  api:
    image: node:18.12.1
    environment:
      - MONGO_URL=mongodb://mongodb/cinema_listings
      - MONGO_DB_NAME=cinema_listings
      - PORT=4000
      - BCRYPT_SALT
      - JWT_SECRET
    depends_on:
      - mongodb
    volumes:
      - type: bind
        source: .
        target: /usr/src
    ports:
      - 8009:4000
    command: >
      bash -c "cd /usr/src/packages/api
      && yarn run dev-inspect"

  front:
    image: node:18.12.1
    environment:
      - NEXT_PUBLIC_API_CLIENT_URL=http://localhost:8009/graphql
      - API_SERVER_URL=http://api:4000/graphql
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - api
    ports:
      - 8008:3000
    command: bash -c "cd packages/front && yarn && yarn run dev"

  mongodb:
    image: mongo:5
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 8001:27017
    command: mongod --logpath=/dev/null
